logs_path: '/<path>/<file>.log'
pg_params:
  host: '<host>'
  database: '<db>'
  user: '<user>'
  #password: ''
ch_params:
  host: '<host>'
  port: '<port>'
  user: '<user>'
  #password: ''
pg_queries:
  dbtables_query: "select table_name from information_schema.tables where table_schema = '<schema>' and table_type = 'BASE TABLE';"
  table_schema_query: "select column_name, data_type from information_schema.columns where table_name = '{name}';"
ch_queries:
  dbtables_query: "show tables from <db>"
  create_table_query: "create table <db>.{name} ({body}) engine = PostgreSQL('<host1>|<host2>|<host3>:5432', '<db>', '{name}', '<user>', '<password>', '<schema>');"
types_mappings:
  "timestamp without time zone": "DateTime64"
  "timestamp with time zone": "DateTime64"
  "numeric": "Float64"
  "bytea": "String"
  "boolean": "Bool"
  "text": "String"
  "date": "Date"
  "double precision": "Float64"
  "integer": "Int64"
  "bigint": "Int64"
  "smallint": "UInt16"
  "character": "String"


